#!/bin/sh
set -e

if [ "$1" = configure ] && ! getent passwd dyapp-node >/dev/null; then
    adduser --system --group --home /var/lib/dyapp-node dyapp-node
fi

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload
    if [ "$1" = configure ] && [ -z "$2" ]; then
        systemctl enable --now dyapp-node.service
    else
        systemctl try-restart dyapp-node.service
    fi
fi
