[package]
name = "dyapp-p2p-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
dyapp-identity = { path = "../identity" }
prost.workspace = true
libp2p = { version = "0.57", features = [
    "autonat", "identify", "kad", "macros", "noise", "quic", "request-response", "tcp", "tokio",
    "yamux",
] }

[build-dependencies]
prost-build.workspace = true
protox.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
