[package]
name = "dyapp-p2p-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
libp2p = { version = "0.57", features = [
    "autonat", "identify", "kad", "macros", "noise", "quic", "tcp", "tokio", "yamux",
] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
