[package]
name = "dyapp-profile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dyapp-identity = { path = "../identity" }
prost.workspace = true
thiserror = "2"

[build-dependencies]
prost-build.workspace = true
protox.workspace = true
