name: ci

on:
  push:
    branches: [main, master, develop]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  required:
    name: matrix
    uses: ./.github/workflows/ci-matrix.yml
